apiVersion: v1
kind: Service
metadata:
  name: ownproject-service
  namespace: ownproject
spec:
  selector:
    app: ownproject-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
